# -*- coding: utf-8 -*-
"""Task7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gINCUwvIkKaMiOhwhZe8JLXxF1zaw2kS
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load SQLite database
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Drop table if exists (to recreate fresh)
cursor.execute("DROP TABLE IF EXISTS sales")

# Create sales table
cursor.execute("""
CREATE TABLE sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL,
    date TEXT
)
""")

# Insert some sample data
sales_data = [
    ("Apples", 30, 1.2, "2025-10-01"),
    ("Bananas", 50, 0.8, "2025-10-01"),
    ("Oranges", 40, 1.0, "2025-10-02"),
    ("Apples", 25, 1.2, "2025-10-03"),
    ("Bananas", 35, 0.8, "2025-10-03"),
    ("Oranges", 20, 1.0, "2025-10-03"),
]
cursor.executemany("INSERT INTO sales (product, quantity, price, date) VALUES (?, ?, ?, ?)", sales_data)
conn.commit()

# 2.Define and run SQL query
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)

# 3. Print results
print("=== Sales Summary ===")
print(df)

# 4. Plot simple bar chart
df.plot(kind='bar', x='product', y='revenue', legend=False, color='skyblue')
plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue ($)")
plt.tight_layout()

# 5. Save chart if needed
plt.savefig("sales_chart.png")
plt.show()

